insert into products (sku,name,category,description,price,top_notes,heart_notes,base_notes,duration,sizes,images) values
('TWR-HNG-001', "TAWAR Noir Hanging", 'hanging', "A dark, elegant cabin fragrance with warm woods and amber.", 299, ARRAY["Bergamot", "Black Pepper"]::text[], ARRAY["Jasmine", "Leather"]::text[], ARRAY["Amber", "Cedar"]::text[], '45 days', '[{"label":"Standard","price":299},{"label":"Premium","price":449}]'::jsonb, ARRAY['https://images.unsplash.com/photo-1615634260167-c8cdede054de?auto=format&fit=crop&w=1200&q=80']::text[] ),
('TWR-HNG-002', "TAWAR Oud Luxe Hanging", 'hanging', "Rich oud-inspired luxury for a sophisticated drive.", 499, ARRAY["Saffron", "Cardamom"]::text[], ARRAY["Rose", "Oud"]::text[], ARRAY["Musk", "Amber"]::text[], '60 days', '[{"label":"Standard","price":499},{"label":"Premium","price":649}]'::jsonb, ARRAY['https://images.unsplash.com/photo-1615634260167-c8cdede054de?auto=format&fit=crop&w=1200&q=80']::text[] ),
('TWR-ACV-001', "TAWAR Royal AC Vent", 'ac-vent', "A compact vent diffuser with refined citrus and woods.", 399, ARRAY["Lemon", "Grapefruit"]::text[], ARRAY["Lavender", "Violet"]::text[], ARRAY["Vetiver", "Cedar"]::text[], '30 days', '[{"label":"Standard","price":399},{"label":"Premium","price":549}]'::jsonb, ARRAY['https://images.unsplash.com/photo-1615634260167-c8cdede054de?auto=format&fit=crop&w=1200&q=80']::text[] ),
('TWR-ACV-002', "TAWAR Gold AC Vent", 'ac-vent', "Smooth, modern fragrance designed for everyday commuting.", 449, ARRAY["Orange", "Pink Pepper"]::text[], ARRAY["Iris", "Geranium"]::text[], ARRAY["Tonka", "Sandalwood"]::text[], '35 days', '[{"label":"Standard","price":449},{"label":"Premium","price":599}]'::jsonb, ARRAY['https://images.unsplash.com/photo-1615634260167-c8cdede054de?auto=format&fit=crop&w=1200&q=80']::text[] ),
('TWR-SPR-001', "TAWAR Drive Spray", 'spray', "Fine mist cabin spray for an instant fragrance refresh.", 349, ARRAY["Lime", "Mint"]::text[], ARRAY["Aromatic Herbs"]::text[], ARRAY["Musk", "Amber"]::text[], 'Up to 500 sprays', '[{"label":"Standard","price":349},{"label":"Premium","price":499}]'::jsonb, ARRAY['https://images.unsplash.com/photo-1615634260167-c8cdede054de?auto=format&fit=crop&w=1200&q=80']::text[] ),
('TWR-SPR-002', "TAWAR Leather Spray", 'spray', "A premium leather-and-woods cabin mist.", 549, ARRAY["Apple", "Saffron"]::text[], ARRAY["Leather", "Rose"]::text[], ARRAY["Patchouli", "Musk"]::text[], 'Up to 500 sprays', '[{"label":"Standard","price":549},{"label":"Premium","price":699}]'::jsonb, ARRAY['https://images.unsplash.com/photo-1615634260167-c8cdede054de?auto=format&fit=crop&w=1200&q=80']::text[] ),
('TWR-CARD-001', "TAWAR Signature Card", 'fragrance-cards', "Minimal fragrance cards with a clean signature profile.", 299, ARRAY["Pear", "Bergamot"]::text[], ARRAY["Peony", "Lily"]::text[], ARRAY["Musk", "Sandalwood"]::text[], '30 days', '[{"label":"Standard","price":299},{"label":"Premium","price":449}]'::jsonb, ARRAY['https://images.unsplash.com/photo-1615634260167-c8cdede054de?auto=format&fit=crop&w=1200&q=80']::text[] ),
('TWR-CARD-002', "TAWAR Fresh Card", 'fragrance-cards', "Bright, fresh fragrance card for daily drives.", 299, ARRAY["Lemon", "Mint"]::text[], ARRAY["Marine Notes"]::text[], ARRAY["White Musk", "Cedar"]::text[], '30 days', '[{"label":"Standard","price":299},{"label":"Premium","price":449}]'::jsonb, ARRAY['https://images.unsplash.com/photo-1615634260167-c8cdede054de?auto=format&fit=crop&w=1200&q=80']::text[] ),
('TWR-CMB-001', "TAWAR Executive Combo", 'hanging', "A curated duo for a polished executive cabin.", 799, ARRAY["Bergamot", "Cinnamon"]::text[], ARRAY["Leather", "Clove"]::text[], ARRAY["Amber", "Cedar"]::text[], '60 days', '[{"label":"Standard","price":799},{"label":"Premium","price":949}]'::jsonb, ARRAY['https://images.unsplash.com/photo-1615634260167-c8cdede054de?auto=format&fit=crop&w=1200&q=80']::text[] ),
('TWR-CMB-002', "TAWAR Royal Duo", 'ac-vent', "Two complementary vent fragrances for home and travel.", 899, ARRAY["Mandarin", "Pepper"]::text[], ARRAY["Jasmine", "Orris"]::text[], ARRAY["Vanilla", "Sandalwood"]::text[], '60 days', '[{"label":"Standard","price":899},{"label":"Premium","price":1049}]'::jsonb, ARRAY['https://images.unsplash.com/photo-1615634260167-c8cdede054de?auto=format&fit=crop&w=1200&q=80']::text[] ),
('TWR-CMB-003', "TAWAR Master Combo", 'hanging', "The complete TAWAR cabin ritual: hanging, vent and spray.", 1499, ARRAY["Bergamot", "Saffron"]::text[], ARRAY["Oud", "Leather"]::text[], ARRAY["Amber", "Musk"]::text[], '90 days', '[{"label":"Standard","price":1499},{"label":"Premium","price":1649}]'::jsonb, ARRAY['https://images.unsplash.com/photo-1615634260167-c8cdede054de?auto=format&fit=crop&w=1200&q=80']::text[] ),
('TWR-CMB-004', "TAWAR Discovery Set", 'fragrance-cards', "Four signature cards to discover your TAWAR profile.", 699, ARRAY["Citrus", "Apple"]::text[], ARRAY["Rose", "Lavender"]::text[], ARRAY["Musk", "Vetiver"]::text[], '30 days', '[{"label":"Standard","price":699},{"label":"Premium","price":849}]'::jsonb, ARRAY['https://images.unsplash.com/photo-1615634260167-c8cdede054de?auto=format&fit=crop&w=1200&q=80']::text[] )
on conflict (sku) do nothing;
